name: Build cloudflared for FreeBSD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FreeBSD QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-user-static

    - name: Set up FreeBSD environment
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker run --name freebsd -d freebsd:12.2 tail -f /dev/null
        docker cp . freebsd:/workspace
        docker exec freebsd sh -c "pkg install -y git go"
        docker exec freebsd sh -c "cd /workspace && env GOOS=freebsd GOARCH=amd64 go build -o cloudflared"

    - name: Retrieve built binary
      run: docker cp freebsd:/workspace/cloudflared .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: cloudflared-freebsd
        path: ./cloudflared
