name: Build cloudflared for FreeBSD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for FreeBSD
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 使用 cloudflared 需要的 Go 版本

      # Step 3: Install cross-compilation tools
      - name: Install FreeBSD cross-compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12 make
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

      # Step 4: Cross-compile for FreeBSD
      - name: Build for FreeBSD
        run: |
          GOOS=freebsd GOARCH=amd64 go build -o cloudflared-freebsd ./cmd/cloudflared

      # Step 5: Upload the binary as an artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cloudflared-freebsd
          path: cloudflared-freebsd
